/** Bilingual UI copy (English + Myanmar) for simple switching in the app shell. */
export type Locale = 'en' | 'my'

export function pick(entry: { en: string; my: string }, locale: Locale): string {
  return locale === 'my' ? entry.my : entry.en
}

export const ui = {
  common: {
    loading: { en: 'Loading…', my: 'ခဏစောင့်ပါ…' },
    openMenu: { en: 'Open menu', my: 'မီနူးဖွ်င့်' },
    closeMenu: { en: 'Close menu', my: 'မီနူးပိတ်' },
    continueShopping: { en: 'Continue shopping', my: 'စာအုပ်ပြန်ရှာရန်' },
    browseBooks: { en: 'Browse books', my: 'စာအုပ်ကြည့်ရန်' },
    viewDetails: { en: 'View details', my: 'အသေးစိတ်ကြည့်ရန်' },
    total: { en: 'Total', my: 'စုစုပေါင်း' },
    subtotal: { en: 'Subtotal', my: 'ပမာဏ' },
    remove: { en: 'Remove', my: 'ဖြုတ်ရန်' },
    quantity: { en: 'Quantity', my: 'အရေအတွက်' },
    itemsCount: { en: 'items', my: 'ခု' },
    itemCount: { en: 'item', my: 'ခု' },
    themeLight: { en: 'Light screen', my: 'အလင်းရောင်' },
    themeDark: { en: 'Dark screen', my: 'မှောင်ရေ' },
    language: { en: 'Language', my: 'ဘာသာစကား' },
    english: { en: 'English', my: 'အင်္ဂလိပ်' },
    myanmar: { en: 'Myanmar', my: 'မြန်မာ' },
    payError: {
      en: 'Payment could not start. Please try again.',
      my: 'ငွေပေးချေ မစတင်နိုင်ပါ။ ပြန်စမ်းကြည့်ပါ။',
    },
  },
  nav: {
    books: { en: 'Books', my: 'စာအုပ်များ' },
    orders: { en: 'My orders', my: 'မှာယူမှုများ' },
    cart: { en: 'Cart', my: 'ခြင်းတောင်း' },
    addBook: { en: 'Add new book', my: 'စာအုပ်အသစ်' },
    signIn: { en: 'Sign in', my: 'ဝင်ရန်' },
    signOut: { en: 'Sign out', my: 'ထွက်ရန်' },
    brand: { en: 'MyatPwint', my: 'မြတ်ပွင့်' },
  },
  bookLoad: {
    notFound: { en: 'Book not found', my: 'စာအုပ်မတွေ့ပါ' },
    failed: { en: 'Could not load this book', my: 'စာအုပ် မဖတ်နိုင်ပါ' },
  },
  booksPage: {
    title: { en: 'Myat Pwint books', my: 'မြတ်ပွင့် စာအုပ်များ' },
    subtitle: {
      en: 'Tap a book cover to open it. Price and details are on the next page.',
      my: 'စာအုပ်ပုံကို နှိပ်ပါ။ ဈေးနှုန်း နှင့် အသေးစိတ် နောက်စာမျက်နှာတွင် ပါသည်။',
    },
    noBooks: { en: 'No books yet', my: 'စာအုပ်မရှိသေးပါ' },
    noBooksHint: { en: 'Please try again later.', my: 'နောက်မှ ပြန်စမ်းကြည့်ပါ။' },
    noImage: { en: 'No image', my: 'ပုံမရှိ' },
  },
  bookDetail: {
    back: { en: 'Back to books', my: 'စာအုပ်များသို့ ပြန်သွားရန်' },
    byAuthor: { en: 'by', my: 'စာရေးသူ' },
    about: { en: 'About this book', my: 'ဤစာအုပ်အကြောင်း' },
    readMore: { en: 'Read more', my: 'ပိုဖတ်ရန်' },
    showLess: { en: 'Show less', my: 'လျှော့ပြရန်' },
    edition: { en: 'Edition', my: 'အယ်ဒေရှင်း' },
    price: { en: 'Price', my: 'ဈေးနှုန်း' },
    addToCart: { en: 'Add to cart', my: 'ခြင်းတောင်းထည့်ရန်' },
    removeFromCart: { en: 'Remove from cart', my: 'ခြင်းတောင်းမှ ဖယ်ရန်' },
    buyNow: { en: 'Buy now', my: 'ယခုဝယ်ရန်' },
  },
  cart: {
    title: { en: 'Your cart', my: 'ခြင်းတောင်း' },
    emptyTitle: { en: 'Your cart is empty', my: 'ခြင်းတောင်းမှာ မရှိပါ' },
    emptyHint: {
      en: 'Choose books first, then pay here.',
      my: 'စာအုပ်ရွေးပြီးမှ ငွေပေးချေရန်။',
    },
    payKbz: { en: 'Pay with KBZPay', my: 'KBZPay ငွေပေးချေရန်' },
    paySignIn: { en: 'Sign in to pay', my: 'ငွေပေးချေရန် ဝင်ရန်' },
    payRedirect: { en: 'Going to payment…', my: 'ငွေပေးချေစက်မ်နှုန်း…' },
    shoppingCart: { en: 'Shopping cart', my: 'ခြင်းတောင်း' },
    emptyShort: { en: 'Cart is empty', my: 'ခြင်းတောင်း ဗလာ' },
    clearAll: { en: 'Clear all', my: 'အားလုံးဖျက်ရန်' },
    closeCart: { en: 'Close cart', my: 'ပိတ်ရန်' },
    viewCart: { en: 'Open full cart', my: 'ခြင်းတောင်း အပြည့်ကြည့်ရန်' },
    cartCount: { en: 'in cart', my: 'ခု' },
  },
  auth: {
    loginHelp: {
      en: 'Use the email and password you registered with.',
      my: 'သင်မှတ်ပုံတင်ထားသော အီးမေးလ် နှင့် စကားဝှက်ကို သုံးပါ။',
    },
    registerHelp: {
      en: 'Fill in all boxes. You can use this account to buy books.',
      my: 'အကွက်အားလုံး ဖြည့်ပါ။ စာအုပ်ဝယ်ရန် ဤအကောင့်သုံးနိုင်ပါသည်။',
    },
    loginTitle: { en: 'Sign in to MyatPwint', my: 'မြတ်ပွင့် သို့ ဝင်ရန်' },
    loginSubtitle: { en: 'Myanmar digital books', my: 'ဒီဂျစ်တယ် မြန်မာစာအုပ်များ' },
    registerTitle: { en: 'Join MyatPwint', my: 'မြတ်ပွင့် တွင် မှတ်ပုံတင်ရန်' },
    registerSubtitle: { en: 'Create your account', my: 'အကောင့်ဖွင့်ရန်' },
    email: { en: 'Email', my: 'အီးမေးလ်' },
    password: { en: 'Password', my: 'စကားဝှက်' },
    fullName: { en: 'Full name', my: 'အမည်အပြည့်အစုံ' },
    signInCta: { en: 'Sign in', my: 'ဝင်ရန်' },
    signingIn: { en: 'Signing in…', my: 'ဝင်နေသည်…' },
    signUpCta: { en: 'Create account', my: 'မှတ်ပုံတင်ရန်' },
    creating: { en: 'Creating…', my: 'ဖန်တီးနေသည်…' },
    noAccount: { en: "No account? Sign up", my: 'အကောင့်မရှိဘူးလား? မှတ်ပုံတင်ပါ' },
    hasAccount: { en: 'Already have an account? Sign in', my: 'အကောင့်ရှိပြီးသားလား? ဝင်ပါ' },
    emailPh: { en: 'Your email', my: 'အီးမေးလ်' },
    passwordPh: { en: 'Your password', my: 'စကားဝှက်' },
    passwordHint: { en: 'At least 6 characters', my: 'အနည်းဆုံး စာလုံး ၆ လုံး' },
    roleLabel: { en: 'I am a', my: 'ကျွန်ုပ် သည်' },
    customer: { en: 'Reader (buy books)', my: 'စာဖတ်သူ (ဝယ်သူ)' },
    publisher: { en: 'Publisher', my: 'ထုတ်ဝေသူ' },
    goLogin: { en: 'Go to sign in →', my: 'ဝင်ရန် သွားပါ →' },
    namePh: { en: 'Your name', my: 'အမည်' },
  },
  orders: {
    title: { en: 'My orders', my: 'မှာယူမှုများ' },
    noneTitle: { en: 'No orders yet', my: 'မှာယူမှုမရှိသေးပါ' },
    noneHint: { en: 'When you buy books, your orders show here.', my: 'စာအုပ်ဝယ်လျှင် ဤနေရာတွင် ပေါ်လာပါမည်။' },
    orderId: { en: 'Order ID', my: 'မှာယူမှုနံပါတ်' },
    orderDate: { en: 'Date', my: 'ရက်စွဲ' },
    itemsLabel: { en: 'Items', my: 'ပစ္စည်းများ' },
    receiptTitle: { en: 'Order receipt', my: 'မှာယူမှုဖြတ်ပိုင်း' },
    paymentDate: { en: 'Paid on', my: 'ငွေပေးချေချိန်' },
    paymentMethod: { en: 'Payment method', my: 'ငွေပေးချေနာမည်' },
    transactionId: { en: 'Transaction ID', my: 'လုပ်ငန်းစဉ် နံပါတ်' },
    allOrders: { en: 'All orders', my: 'မှာယူမှုအားလုံး' },
    checkPayment: { en: 'Check payment', my: 'ငွေပေးချေမှု စစ်ဆေးရန်' },
    checking: { en: 'Checking…', my: 'စစ်ဆေးနေသည်…' },
    paidAmount: { en: 'Amount paid', my: 'ပေးချေငွေ' },
    qty: { en: 'Qty', my: 'အရေ' },
    notFound: { en: 'Order not found', my: 'မှာယူမှု မတွေ့ပါ' },
    loadError: { en: 'Could not load order', my: 'မှာယူမှု မဖတ်နိုင်ပါ' },
    unauthorized: { en: 'Not allowed', my: 'ခွင့်မပြုပါ' },
  },
  orderStatus: {
    pending: { en: 'Pending', my: 'စောင့်ဆိုင်း' },
    completed: { en: 'Paid', my: 'ပြီးစီး' },
    failed: { en: 'Failed', my: 'မအောင်မြင်' },
    expired: { en: 'Expired', my: 'သက်သေကုန်' },
    cancelled: { en: 'Cancelled', my: 'ပယ်ဖျက်' },
  },
} as const

export function orderStatusLabel(
  status: keyof typeof ui.orderStatus,
  locale: Locale,
): string {
  return pick(ui.orderStatus[status], locale)
}
